-- CareerCraft Pro — base schema.
--
-- Run the migrations in this folder in order, in the Supabase SQL Editor.
-- Every statement is idempotent (`if not exists` / guarded `alter`), so this
-- is safe to run against the live database, which already holds these tables:
-- the missing pieces (indexes, constraints, RLS, comments) get added, and
-- nothing existing is dropped or rewritten.
--
-- Access model: the app talks to Postgres only through the service-role key
-- (src/lib/supabase-admin.ts), and admin auth is a signed cookie checked in
-- the Next.js layer (src/lib/admin-session.ts) — there are no Supabase Auth
-- users. So every table below enables RLS and defines no policies at all:
-- the service role bypasses RLS, and anon/authenticated callers holding the
-- publishable key can read nothing, even if that key leaks into a bundle.

create extension if not exists pgcrypto;

-- Shared touch-trigger, so a row's updated_at is right even if a caller
-- forgets to set it.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ---------------------------------------------------------------------------
-- cv_events — one row per CV generated by the CV Builder / CV Transform.
-- ---------------------------------------------------------------------------
-- `data` is the whole builder payload, kept verbatim so the admin can reopen
-- a past CV and regenerate it (see /api/admin/cv/[id]).

create table if not exists public.cv_events (
  id         uuid        primary key default gen_random_uuid(),
  name       text        not null,
  template   text        not null,
  data       jsonb       not null default '{}'::jsonb,
  paid       boolean     not null default true,
  created_at timestamptz not null default now()
);

alter table public.cv_events add column if not exists data       jsonb       not null default '{}'::jsonb;
alter table public.cv_events add column if not exists paid       boolean     not null default true;
alter table public.cv_events add column if not exists created_at timestamptz not null default now();

-- The admin list is strictly "newest first, capped at N".
create index if not exists cv_events_created_at_idx
  on public.cv_events (created_at desc);

comment on table  public.cv_events is
  'One row per CV download. `paid` is false for admin-created (free) downloads.';
comment on column public.cv_events.data is
  'Full CV builder payload — regenerating a past CV replays this verbatim.';

alter table public.cv_events enable row level security;
revoke all on public.cv_events from anon, authenticated;


-- ---------------------------------------------------------------------------
-- interview_events — one row per interview-prep pack generated.
-- ---------------------------------------------------------------------------

create table if not exists public.interview_events (
  id         uuid        primary key default gen_random_uuid(),
  name       text        not null,
  role       text        not null,
  data       jsonb       not null default '{}'::jsonb,
  paid       boolean     not null default true,
  created_at timestamptz not null default now()
);

alter table public.interview_events add column if not exists data       jsonb       not null default '{}'::jsonb;
alter table public.interview_events add column if not exists paid       boolean     not null default true;
alter table public.interview_events add column if not exists created_at timestamptz not null default now();

create index if not exists interview_events_created_at_idx
  on public.interview_events (created_at desc);

comment on table  public.interview_events is
  'One row per interview-prep pack. `paid` is false for admin-created (free) packs.';
comment on column public.interview_events.data is
  'Full generated prep pack — reopening a past pack replays this verbatim.';

alter table public.interview_events enable row level security;
revoke all on public.interview_events from anon, authenticated;
